#!/usr/bin/env python3
import sys
from algorithms.runner.alns.alns_commom import setup_alns, get_config
from algorithms.solution_state import SolutionState


def run_alns() -> None:
    k = 2
    path = sys.argv[1]
    configuration = sys.argv[2:]
    configs = get_config(configuration)

    initial_S = SolutionState(path, k)
    alns = setup_alns(configs)

    solution = alns.execute(initial_S)
    objective_val = len(solution.S)
    alns.clear()

    print(objective_val)


if __name__ == "__main__":
    run_alns()
